linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - structcheck
    - varcheck
    - deadcode
    - gocyclo
    - dupl
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell

issues:
  exclude-rules:
    - path: cmd/drago/main.go
      linters:
        - unused
